# Generated by Django 4.0.6 on 2022-07-31 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_test_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 21, 7, 10, 798476)),
        ),
    ]
