# Generated by Django 4.0.6 on 2022-08-01 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_test_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 17, 33, 28, 133153)),
        ),
    ]
