# Generated by Django 4.0.6 on 2022-08-02 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_test_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 13, 43, 41, 935486)),
        ),
    ]
